In [1]:
import pandas as pd
import numpy as np

# Load Dashboard Dataset
df = pd.read_csv("Dashboard_Data.csv")

# Convert date columns
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Quantity,Discount,Profit,Year,Month,Month Name,Quarter,Day,Day Name,Shipping Days
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,2,0.00,41.9136,2016,11,November,4,8,Tuesday,3
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,3,0.00,219.5820,2016,11,November,4,8,Tuesday,3
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,2,0.00,6.8714,2016,6,June,2,12,Sunday,4
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,5,0.45,-383.0310,2015,10,October,4,11,Sunday,7
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,2,0.20,2.5164,2015,10,October,4,11,Sunday,7

In [2]:
#overall business KPIs
total_sales = df["Sales"].sum()
total_profit = df["Profit"].sum()
total_orders = df["Order ID"].nunique()
total_customers = df["Customer ID"].nunique()
avg_order_value = total_sales / total_orders

print("="*50)
print("BUSINESS KPIs")
print("="*50)

print(f"Total Sales        : ${total_sales:,.2f}")
print(f"Total Profit       : ${total_profit:,.2f}")
print(f"Total Orders       : {total_orders}")
print(f"Total Customers    : {total_customers}")
print(f"Average Order Value: ${avg_order_value:,.2f}")

==================================================
BUSINESS KPIs
==================================================
Total Sales        : $2,297,200.86
Total Profit       : $286,397.02
Total Orders       : 5009
Total Customers    : 793
Average Order Value: $458.61

In [3]:
#top selling categories
category_sales = df.groupby("Category")["Sales"].sum().sort_values(ascending=False)

print("\nTop Selling Category")
print(category_sales)

best_category = category_sales.idxmax()

print(f"\nBest Category: {best_category}")

Top Selling Category
Category
Technology         836154.0330
Furniture          741999.7953
Office Supplies    719047.0320
Name: Sales, dtype: float64

Best Category: Technology

In [4]:
#most profitable category
category_profit = df.groupby("Category")["Profit"].sum().sort_values(ascending=False)

print(category_profit)

print(f"\nMost Profitable Category: {category_profit.idxmax()}")

Category
Technology         145454.9481
Office Supplies    122490.8008
Furniture           18451.2728
Name: Profit, dtype: float64

Most Profitable Category: Technology

In [5]:
#top 10 products
top_products = (
    df.groupby("Product Name")["Sales"]
      .sum()
      .sort_values(ascending=False)
      .head(10)
)

print(top_products)

Product Name
Canon imageCLASS 2200 Advanced Copier                                          61599.824
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.384
Cisco TelePresence System EX90 Videoconferencing Unit                          22638.480
HON 5400 Series Task Chairs for Big and Tall                                   21870.576
GBC DocuBind TL300 Electric Binding System                                     19823.479
GBC Ibimaster 500 Manual ProClick Binding System                               19024.500
Hewlett Packard LaserJet 3310 Copier                                           18839.686
HP Designjet T520 Inkjet Large Format Printer - 24" Color                      18374.895
GBC DocuBind P400 Electric Binding System                                      17965.068
High Speed Automatic Electric Letter Opener                                    17030.312
Name: Sales, dtype: float64

In [6]:
#best region
region_sales = df.groupby("Region")["Sales"].sum().sort_values(ascending=False)

print(region_sales)

print(f"\nBest Region: {region_sales.idxmax()}")

Region
West       725457.8245
East       678781.2400
Central    501239.8908
South      391721.9050
Name: Sales, dtype: float64

Best Region: West

In [7]:
#best state
state_sales = (
    df.groupby("State")["Sales"]
      .sum()
      .sort_values(ascending=False)
      .head(10)
)

print(state_sales)

State
California      457687.6315
New York        310876.2710
Texas           170188.0458
Washington      138641.2700
Pennsylvania    116511.9140
Florida          89473.7080
Illinois         80166.1010
Ohio             78258.1360
Michigan         76269.6140
Virginia         70636.7200
Name: Sales, dtype: float64

In [8]:
#best customer segment
segment_sales = (
    df.groupby("Segment")["Sales"]
      .sum()
      .sort_values(ascending=False)
)

print(segment_sales)

print(f"\nBest Customer Segment: {segment_sales.idxmax()}")

Segment
Consumer       1.161401e+06
Corporate      7.061464e+05
Home Office    4.296531e+05
Name: Sales, dtype: float64

Best Customer Segment: Consumer

In [9]:
#monthly sales analysis
monthly_sales = (
    df.groupby(df["Order Date"].dt.month_name())["Sales"]
      .sum()
)

months = [
    "January","February","March","April","May","June",
    "July","August","September","October","November","December"
]

monthly_sales = monthly_sales.reindex(months)

print(monthly_sales)

Order Date
January       94924.8356
February      59751.2514
March        205005.4888
April        137762.1286
May          155028.8117
June         152718.6793
July         147238.0970
August       159044.0630
September    307649.9457
October      200322.9847
November     352461.0710
December     325293.5035
Name: Sales, dtype: float64

In [10]:
#highest sales month
best_month = monthly_sales.idxmax()

print("Highest Sales Month:", best_month)

Highest Sales Month: November

In [11]:
monthly_profit = (
    df.groupby(df["Order Date"].dt.month_name())["Profit"]
      .sum()
)

monthly_profit = monthly_profit.reindex(months)

print(monthly_profit)

Order Date
January       9134.4461
February     10294.6107
March        28594.6872
April        11587.4363
May          22411.3078
June         21285.7954
July         13832.6648
August       21776.9384
September    36857.4753
October      31784.0413
November     35468.4265
December     43369.1919
Name: Profit, dtype: float64

In [12]:
#highest profit month
print("Highest Profit Month:", monthly_profit.idxmax())

Highest Profit Month: December

In [13]:
#shipping performance
df["Shipping Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

print(df["Shipping Days"].describe())

print(f"\nAverage Shipping Time: {df['Shipping Days'].mean():.2f} Days")

count    9994.000000
mean        3.958175
std         1.747567
min         0.000000
25%         3.000000
50%         4.000000
75%         5.000000
max         7.000000
Name: Shipping Days, dtype: float64

Average Shipping Time: 3.96 Days

In [14]:
#discount analysis
discount_profit = (
    df.groupby("Discount")["Profit"]
      .mean()
)

print(discount_profit)

Discount
0.00     66.900292
0.10     96.055074
0.15     27.288298
0.20     24.702572
0.30    -45.679636
0.32    -88.560656
0.40   -111.927429
0.45   -226.646464
0.50   -310.703456
0.60    -43.077212
0.70    -95.874060
0.80   -101.796797
Name: Profit, dtype: float64

In [15]:
#top 10 customers
customers = (
    df.groupby("Customer Name")["Sales"]
      .sum()
      .sort_values(ascending=False)
      .head(10)
)

print(customers)

Customer Name
Sean Miller           25043.050
Tamara Chand          19052.218
Raymond Buch          15117.339
Tom Ashbrook          14595.620
Adrian Barton         14473.571
Ken Lonsdale          14175.229
Sanjit Chand          14142.334
Hunter Lopez          12873.298
Sanjit Engle          12209.438
Christopher Conant    12129.072
Name: Sales, dtype: float64

In [16]:
#market trend score
monthly = (
    df.groupby(df["Order Date"].dt.to_period("M"))["Sales"]
      .sum()
)

monthly = monthly.reset_index()

monthly["Order Date"] = monthly["Order Date"].astype(str)

monthly["Growth %"] = (
    monthly["Sales"].pct_change() * 100
)

monthly.head()

  Order Date      Sales     Growth %
0    2014-01  14236.895          NaN
1    2014-02   4519.892   -68.252263
2    2014-03  55691.009  1132.131409
3    2014-04  28295.345   -49.192257
4    2014-05  23648.287   -16.423401

In [17]:
#trend classification
def classify(growth):

    if pd.isna(growth):
        return "No Data"

    elif growth > 10:
        return "Growing 📈"

    elif growth < -10:
        return "Declining 📉"

    else:
        return "Stable ➖"

monthly["Trend"] = monthly["Growth %"].apply(classify)

monthly

   Order Date        Sales     Growth %        Trend
0     2014-01   14236.8950          NaN      No Data
1     2014-02    4519.8920   -68.252263  Declining 📉
2     2014-03   55691.0090  1132.131409    Growing 📈
3     2014-04   28295.3450   -49.192257  Declining 📉
4     2014-05   23648.2870   -16.423401  Declining 📉
5     2014-06   34595.1276    46.290205    Growing 📈
6     2014-07   33946.3930    -1.875220     Stable ➖
7     2014-08   27909.4685   -17.783699  Declining 📉
8     2014-09   81777.3508   193.009345    Growing 📈
9     2014-10   31453.3930   -61.537770  Declining 📉
10    2014-11   78628.7167   149.984848    Growing 📈
11    2014-12   69545.6205   -11.551882  Declining 📉
12    2015-01   18174.0756   -73.867405  Declining 📉
13    2015-02   11951.4110   -34.239236  Declining 📉
14    2015-03   38726.2520   224.030794    Growing 📈
15    2015-04   34195.2085   -11.700186  Declining 📉
16    2015-05   30131.6865   -11.883308  Declining 📉
17    2015-06   24797.2920   -17.703604  Declining 📉
18    2015-07   28765.3250    16.001880    Growing 📈
19    2015-08   36898.3322    28.273650    Growing 📈
20    2015-09   64595.9180    75.064601    Growing 📈
21    2015-10   31404.9235   -51.382495  Declining 📉
22    2015-11   75972.5635   141.912907    Growing 📈
23    2015-12   74919.5212    -1.386082     Stable ➖
24    2016-01   18542.4910   -75.250121  Declining 📉
25    2016-02   22978.8150    23.925178    Growing 📈
26    2016-03   51715.8750   125.058929    Growing 📈
27    2016-04   38750.0390   -25.071288  Declining 📉
28    2016-05   56987.7280    47.064957    Growing 📈
29    2016-06   40344.5340   -29.204874  Declining 📉
30    2016-07   39261.9630    -2.683315     Stable ➖
31    2016-08   31115.3743   -20.749316  Declining 📉
32    2016-09   73410.0249   135.928465    Growing 📈
33    2016-10   59687.7450   -18.692651  Declining 📉
34    2016-11   79411.9658    33.045679    Growing 📈
35    2016-12   96999.0430    22.146634    Growing 📈
36    2017-01   43971.3740   -54.668239  Declining 📉
37    2017-02   20301.1334   -53.831023  Declining 📉
38    2017-03   58872.3528   189.995399    Growing 📈
39    2017-04   36521.5361   -37.964878  Declining 📉
40    2017-05   44261.1102    21.191809    Growing 📈
41    2017-06   52981.7257    19.702659    Growing 📈
42    2017-07   45264.4160   -14.565984  Declining 📉
43    2017-08   63120.8880    39.449249    Growing 📈
44    2017-09   87866.6520    39.203764    Growing 📈
45    2017-10   77776.9232   -11.483001  Declining 📉
46    2017-11  118447.8250    52.291734    Growing 📈
47    2017-12   83829.3188   -29.226798  Declining 📉

In [18]:
#overall trend
latest = monthly.iloc[-1]

print("="*40)

print("LATEST MARKET STATUS")

print("="*40)

print("Month :", latest["Order Date"])

print("Growth :", round(latest["Growth %"],2),"%")

print("Trend :", latest["Trend"])

========================================
LATEST MARKET STATUS
========================================
Month : 2017-12
Growth : -29.23 %
Trend : Declining 📉

In [19]:
#business recommendations
print("="*50)
print("BUSINESS RECOMMENDATIONS")
print("="*50)

print(f"✅ Focus on {best_category} products as they generate the highest sales.")

print(f"✅ Increase inventory in the {region_sales.idxmax()} region.")

print(f"✅ Target {segment_sales.idxmax()} customers with marketing campaigns.")

print(f"✅ Prepare additional stock before {best_month}, which has the highest sales.")

if latest["Trend"] == "Growing 📈":
    print("✅ Market demand is increasing. Consider expanding inventory.")

elif latest["Trend"] == "Declining 📉":
    print("⚠️ Sales are declining. Review pricing, promotions, and marketing strategies.")

else:
    print("ℹ️ Sales are relatively stable. Continue monitoring trends.")

==================================================
BUSINESS RECOMMENDATIONS
==================================================
✅ Focus on Technology products as they generate the highest sales.
✅ Increase inventory in the West region.
✅ Target Consumer customers with marketing campaigns.
✅ Prepare additional stock before November, which has the highest sales.
⚠️ Sales are declining. Review pricing, promotions, and marketing strategies.

In [20]:
#save insights
summary = {
    "Total Sales": total_sales,
    "Total Profit": total_profit,
    "Top Category": best_category,
    "Best Region": region_sales.idxmax(),
    "Best Segment": segment_sales.idxmax(),
    "Best Month": best_month,
    "Market Trend": latest["Trend"]
}

summary_df = pd.DataFrame([summary])

summary_df.to_csv("business_summary.csv", index=False)

print("Business Summary Saved Successfully!")

Business Summary Saved Successfully!